name: PPGMobile
options:
  bundleIdPrefix: com.2witstudios
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: "1.0.0"

targets:
  PPGMobile:
    type: application
    platform: iOS
    sources:
      - path: PPGMobile
        excludes:
          - "**/*Tests.swift"
    dependencies:
      - package: SwiftTerm
    info:
      path: PPGMobile/Info.plist
      properties:
        NSLocalNetworkUsageDescription: "PPG Mobile connects to the ppg serve daemon on your local network to manage agents and view terminal output."
        NSBonjourServices:
          - "_http._tcp"
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.2witstudios.ppg-mobile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true

schemes:
  PPGMobile:
    build:
      targets:
        PPGMobile: all
